import { chromium } from 'playwright-core';
const browser = await chromium.connectOverCDP('http://127.0.0.1:9333');
const page = browser.contexts()[0].pages()[0];
page.on('console', m => { if (m.type() === 'error') console.log('[err]', m.text().slice(0, 250)); });
await page.click('#ob-next'); await page.click('#ob-next'); await new Promise(r=>setTimeout(r,600));
await page.fill('#ob-offline-name', 'BlockBoxTester');
await page.click('#ob-offline-add');
await new Promise(r=>setTimeout(r,4000));
console.log('body after add:', (await page.evaluate(() => document.body.innerText)).split('\n').slice(10,34).join(' | '));
const accs = await page.evaluate(async () => window.bb.raw.invoke('accounts.list'));
console.log('accounts:', JSON.stringify(accs).slice(0, 200));
await browser.close(); process.exit(0);
