import { chromium } from 'playwright-core';
const browser = await chromium.connectOverCDP('http://127.0.0.1:9333');
const page = browser.contexts()[0].pages()[0];
const insts = (await page.evaluate(async () => window.bb.raw.invoke('instances.list'))).v;
const X = insts.find(i => i.loader === 'vanilla') || insts[0];
const setR = await page.evaluate(async (p) => window.bb.raw.invoke('instances.setBoundAccount', p), { id: X.id, accountId: 'test-account' });
console.log('setBoundAccount:', JSON.stringify(setR).slice(0, 150));
const got = await page.evaluate(async (p) => window.bb.raw.invoke('instances.get', p), { id: X.id });
console.log('boundAccountId:', JSON.stringify(got.v?.boundAccountId), 'instance keys:', Object.keys(got.v || {}).join(','));
await browser.close(); process.exit(0);
