import { chromium } from 'playwright-core';
import crypto from 'crypto';
import fs from 'fs';
const browser = await chromium.connectOverCDP('http://127.0.0.1:9333');
const page = browser.contexts()[0].pages()[0];
const dest = '/tmp/校验探测.json';
const url = 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json';
fs.rmSync(dest, { force: true });
const wrong = await page.evaluate(([u, d]) => window.bb.raw.invoke('downloads.testDownload', { url: u, dest: d, sha1: 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeef' }).then(() => 'RESOLVED').catch((e) => 'REJECTED: ' + e.message), [url, dest]);
console.log('错sha1 →', wrong);
console.log('文件存在:', fs.existsSync(dest));
const list = await page.evaluate(async () => window.bb.raw.invoke('downloads.list'));
for (const t of list.v) console.log('任务:', t.state, '|', (t.error || '').slice(0, 70));
await browser.close(); process.exit(0);
