import { spawn } from 'child_process';
import path from 'path';
const ROOT = process.cwd();
const DATA = '/var/folders/2t/ttl2zpb50173wjdkrjzbwc140000gn/T/方块 盒子(增强测试)';
const child = spawn(path.join(ROOT, 'node_modules/.bin/electron'), ['.', '--remote-debugging-port=9333'], { cwd: ROOT, env: { ...process.env, BLOCKBOX_DATA_DIR: DATA }, stdio: 'ignore' });
await new Promise(r => setTimeout(r, 9000));
child.kill('SIGKILL');
await new Promise(r => setTimeout(r, 1500));
const child2 = spawn(path.join(ROOT, 'node_modules/.bin/electron'), ['.', '--remote-debugging-port=9335'], { cwd: ROOT, env: { ...process.env, BLOCKBOX_DATA_DIR: DATA }, stdio: ['ignore', 'pipe', 'pipe'] });
child2.stdout.on('data', (d) => console.log('[app2-out]', d.toString().slice(0, 200)));
child2.stderr.on('data', (d) => console.log('[app2-err]', d.toString().slice(0, 300)));
await new Promise(r => setTimeout(r, 12000));
console.log('app2 alive?', (() => { try { child2.kill(0); return true; } catch { return false; } })());
process.exit(0);
